### ISSUE TITLE
homebrew package?

### ISSUE THREAD

**Issue by turbo-cafe** [leafclick/pgmig#1]
homebrew package would help distributing pgmig to its users. Here's a documentation https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by turbo-cafe** [comment]
fingers crossed... https://github.com/Homebrew/linuxbrew-core/pull/22185

**Comment by katox** [comment]
A simpler distribution of the pgmig binary would be nice. Graal tooling doesn't make it very straightforward though.
